### ISSUE TITLE
HMR is not working in html files

### ISSUE THREAD

**Issue by jshikanova** [IndexXuan/vite-plugin-mpa#1]
Hello

This plugin is very useful. I don't think it is supposed to work with vanilla only projects, but it's actually does.
But I'm having some issues with HMR, it's not working with html files, even I'm getting messages into console that page reloaded

Thanks in advance

https://github.com/jshikanova/vite-vanilla-mpa

**Comment by IndexXuan** [comment]
I will check it later. Not sure it is a vite bug or feature or this plugin bug ?

**Comment by jshikanova** [comment]
@IndexXuan I'm not sure either. Thanks in advance for looking into this

**Comment by IndexXuan** [comment]
@jshikanova I have try vite. the html file not HMR.
you can try any vite project by yarn create @vitejs/app my-app, and edit in html file like <title>
