### ISSUE TITLE
Export broken in .js file

### ISSUE THREAD

**Issue by hville** [IndexXuan/vite-plugin-mpa#10]
`import mpa from '...'`

The result of this is that mpa is an object `{default: [Function]}` instead of being a function.

**Comment by IndexXuan** [comment]
Really! It is just export default function complied by tsc. will check it later. Please give repro demo.

**Comment by hville** [comment]
```
//test.js
import mpa from 'vite-plugin-mpa'
console.log(mpa) //{default: [Function]}
```
Not the first time npm modules based on typescript source are not usable as is.
There must be some gotchas with tsc's export configuration options but I don't know and use typescript to know more

**Comment by IndexXuan** [comment]
![image](https://user-images.githubusercontent.com/6322673/125382011-7cfec300-e3c7-11eb-8918-35636c2b1ba8.png)

I don't know, cannot repro.

1. yarn create vite my-vite-app
2. yarn add vite-plugin-mpa
3. import mpa from 'vite-plugin-mpa' at vite.config.js
4. console.log(mpa)

It is as expected.

**Comment by hville** [comment]
![image](https://user-images.githubusercontent.com/1555569/125384542-121d9f80-e367-11eb-80d0-7be02f6787f0.png)

thanks for checking. I can confirm I still have the same issue (see screen shot)
I will close this issue anyway since I don't intend to use the plugin. A simple tree search is just easier.

**Comment by IndexXuan** [comment]
very interesting.
