### ISSUE TITLE
failed to load config if package of type module

### ISSUE THREAD

**Issue by charlyoleg** [IndexXuan/vite-plugin-mpa#13]
If in the _package.json_ you have the line `'type': 'module',` then the plugin doesn't work anymore. _vite_ fails with the following error message:
```
failed to load config from /.../test_vite_mpa/vite.config.js
error when starting dev server:
TypeError: mpa is not a function
```
This is observed with node v12 and v14.

**Comment by IndexXuan** [comment]
you use require or import for this plugin? I dont know what is if you have type=module, you mean user project pkg has or this plugin pkg has?

**Comment by charlyoleg** [comment]
I use import for the plugin:
```
// vite.config.js
import { defineConfig } from 'vite';
import mpa from 'vite-plugin-mpa';

// @see https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    // ...other plugins
    mpa(/* options */),
  ],
})

```
The issue occurs is the package.json of the user project has _type=module_:
```
{
  "name": "test_vite_mpa",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vite": "^2.5.10",
    "vite-plugin-mpa": "^1.1.0"
  }
}
```

**Comment by IndexXuan** [comment]
I dont know why.
is the `yarn create vite-app` generated repo has `type="module" in package.json ?

**Comment by charlyoleg** [comment]
I haven't also investigated the root cause yet.
No, I haven't use `yarn create vite-app`. I have just installed `vite` and `vite-plugin-mpa` in my project, that happens to have `type: module`.
Notice that _vite_ itself works fine, even in this context of `type: module`.

**Comment by IndexXuan** [comment]
this plugin use tsup to bundle code. like many other vite ecosystem plugin.
dont have much time to figure it out. can you help and PR is welcome.

**Comment by charlyoleg** [comment]
Here a PR that fixes the issue:
https://github.com/IndexXuan/vite-plugin-mpa/pull/15

**Comment by charlyoleg** [comment]
A better PR: https://github.com/IndexXuan/vite-plugin-mpa/pull/16

**Comment by IndexXuan** [comment]
thanks

**Comment by charlyoleg** [comment]
Thanks to you too
