### ISSUE TITLE
fresh page in subpage with vue-router,it's 404 no found. 

### ISSUE THREAD

**Issue by w2819** [IndexXuan/vite-plugin-mpa#2]
this is not a problem in version 0.0.1,but update to 0.3.1,it's went wrong.

**Comment by IndexXuan** [comment]
plz give mini repro demo...

**Comment by w2819** [comment]
[vue3-mpa-app example](https://github.com/w2819/vite-plugin-mpa.git)

**Comment by IndexXuan** [comment]
got it. will figure it out.

**Comment by w2819** [comment]
with version 0.0.1, i can link to http://localhost:3000/subpage/test,but 0.3.1 404.

**Comment by IndexXuan** [comment]
I have no idea after try it. and v0.0.1 is not work as well. you can use createWebHashHistory temp now. html5 history mode with vue-router next maybe have problem. I create an vue-cli project with it, and mpa with vue-router next now work too.

**Comment by IndexXuan** [comment]
Also, you can change 
`history: createWebHistory(),` to
`history: createWebHistory('/subpage/index.html'),`

it works but I don't think so.

**Comment by sstenn** [comment]
+1

I really would like to see this plugin work with `createWebHistory()` !!

**Comment by IndexXuan** [comment]
@sstenn does same code works with `vue-cli` ?

**Comment by sstenn** [comment]
> @sstenn same code works with `vue-cli` ?

Yes!

Setup;
`vite.config.ts`

    mpa({
      open: 'start',
      scanDir: 'src/apps'
    })

`structure`

    src
      - apps
        - app1
          - router
            - index.ts
          - index.html
          - main.ts
          - App.vue
        - app2
      - components
      - assets

`router/index.ts`

    import { createRouter, createWebHashHistory } from "vue-router"

    const routes = [{
      path: '/',
      name: 'Index',
      component: () => import('../views/Index.vue')
    }, 
    {...}]

    const router = createRouter({
      history: createWebHashHistory('/app1'),
      routes
    })

**Comment by IndexXuan** [comment]
@sstenn  what ??? is it `vue-cli` and any issue of your code ?

**Comment by sstenn** [comment]
> @sstenn what ??? is it `vue-cli` and any issue of your code ?

The `createWebHistory()` was working in `vue-cli` with [pages](https://cli.vuejs.org/config/#pages) function. But now I'm not using `vue-cli`. 

The issue is that when refreshing/reloading the browser, I get a 404. But when I'm navigating in the app, it works.

This works: `<router-link to="/about">a</router-link>`
The url looks like this after: `http://localhost:3000/app1/about`

But when I enter the url (`http://localhost:3000/app1/about`) directly in the browser, I get the 404.

When I switch to `createWebHashHistory()`, all works as aspected

**Comment by IndexXuan** [comment]
@sstenn 

> I have no idea after try it. and v0.0.1 is not work as well. you can use createWebHashHistory temp now. html5 history mode with vue-router next maybe have problem. I create an vue-cli project with it, and mpa with vue-router next not work too.

I will figure it out if you provide mini repro demo.

**Comment by sstenn** [comment]
> @sstenn
> 
> > I have no idea after try it. and v0.0.1 is not work as well. you can use createWebHashHistory temp now. html5 history mode with vue-router next maybe have problem. I create an vue-cli project with it, and mpa with vue-router next not work too.
> 
> I will figure it out if you provide mini repro demo.

Here's a small repro demo
https://github.com/sstenn/vite-mpa-repro-demo

I'm using `node 16.8.0`

run `npm install` and then `npm run dev`

**Comment by IndexXuan** [comment]
![image](https://user-images.githubusercontent.com/6322673/132682783-7f1b9fc2-48b7-4b7b-a6d7-99d1c90eb681.png)
It works for me. It is your repro git diff.

**Comment by IndexXuan** [comment]
Use `hash mode` or you should handle createWebHistory(**base**) carefully. both development and deploy.

**Comment by sstenn** [comment]
> It works for me. It is your repro git diff.

This work. But the url now shows `/app1/index.html/{pages}`... And I rather not want to have `index.html` in the url.

What I need is: `/app1/{pages}`

**Comment by IndexXuan** [comment]
> > It works for me. It is your repro git diff.
> 
> This work. But the url now shows `/app1/index.html/{pages}`... And I rather not want to have `index.html` in the url.
> 
> What I need is: `/app1/{pages}`

all you see is only in development http proxy. when in production deploy, it depends on you nginx config.
and I don't have time handle this recently. sorry. PR is welcome.
