### ISSUE TITLE
page-1 and page-10 are identified as the same？

### ISSUE THREAD

**Issue by 1103409364** [IndexXuan/vite-plugin-mpa#26]
I have two web pages like：

src/pages/page-1/index.html
script type="module" src="/src/pages/page-1/main.ts"></script>

src/pages/page-10/index.html
script type="module" src="/src/pages/page-10/main.ts"></script>

when i open the page-10, the result is to open page-1.

**Comment by jinzhanye** [comment]
same issue, demo1、demo2, always open demo1
