### ISSUE TITLE
When multiple page have their own routing,  I hope I can use my defined hisotry rewirte rules

### ISSUE THREAD

**Issue by perfectyang** [IndexXuan/vite-plugin-mpa#3]
1、![image](https://user-images.githubusercontent.com/8724828/116392542-23b8d600-a853-11eb-908f-0d1723a49d3e.png)

2、![image](https://user-images.githubusercontent.com/8724828/116392838-8316e600-a853-11eb-9d9e-006e29b5a39c.png)

3、![image](https://user-images.githubusercontent.com/8724828/116392902-975ae300-a853-11eb-9879-99e99a35d4b4.png)

4、![image](https://user-images.githubusercontent.com/8724828/116392918-9f1a8780-a853-11eb-93b2-3225fa5e1999.png)

Look these picture, when I use this plugin , I can't define the last rewrite rules. Otherwise, the URL look like strange

**Comment by IndexXuan** [comment]
PR Welcome. any idea of merge rewrite list?

**Comment by IndexXuan** [comment]
any feedback ?

**Comment by IndexXuan** [comment]
closed since to feedback
