### ISSUE TITLE
Would like src/pages/index.html as start page preference

### ISSUE THREAD

**Issue by m4mark** [IndexXuan/vite-plugin-mpa#4]
Hi, I'm wondering what config changes do I need to make so that **src/pages/index.html** becomes the start page in dev and production environments? Thanks in advance.

**Comment by IndexXuan** [comment]
see options.template of 
https://github.com/IndexXuan/vite-plugin-html-template
It is another plugin of mine

**Comment by m4mark** [comment]
Thanks for the quick response. Unfortunately still no index.html file being created in the web root after a build, even though I set up public/index.html. I also tried creating an index.html file in the project root but this also failed to generate an index file in the build root.

Let me know if I am missing the point here or the precise **open** key value to use in vite.config.js?

**Comment by IndexXuan** [comment]
I dont know. but you can use npm script after build to move the dist/index/index.html hourself. this plugin output is the same as vue-cli. out-of-scope for me.

**Comment by m4mark** [comment]
Agreed, but It is a real shame as I really like the work you've done with the plugin. Sincerely much appreciated.
