### ISSUE TITLE
`/src/pages/index/index.html` is generated as `/dist/index/index.html`

### ISSUE THREAD

**Issue by patarapolw** [IndexXuan/vite-plugin-mpa#6]
This is very shaming and big fail.

Furthermore, if there is no `/src/pages/index/main.ts`, `index.html` won't be bundled at all.

Putting `index.html` at `/index.html` doesn't help.

The only solution I have now is `/public/index.html`, but it won't get minified.

**Comment by IndexXuan** [comment]
I can do nonthing with the info you provided. you can check the examples and give mini repro demo（alos use vite-plugin-html-template is suggested.）

**Comment by patarapolw** [comment]
Here, real code. - https://github.com/patarapolw/rep2recall-min/tree/vite-mpa/packages/frontend

**Comment by patarapolw** [comment]
Temporary fix:

```ts
const relocateIndex = (): Plugin => {
  let resolvedConfig: UserConfig
  const dest = (resolvedConfig.build && resolvedConfig.build.outDir) || 'dist'

  return {
    name: 'relocate index/index.html',
    config(config) {
      resolvedConfig = config
    },
    configureServer({ middlewares: app }) {
      app.use((req, res, next) => {
        if (
          req.url &&
          req.method === 'GET' &&
          ['/', '/index.html'].includes(req.url.split('?')[0])
        ) {
          //redirect
          res.statusCode = 302
          res.setHeader('Location', '/index')
          return res.end()
        }
        next()
      })
    },
    closeBundle() {
      fs.rename(
        path.resolve(dest, 'index/index.html'),
        path.resolve(dest, 'index.html'),
        () => {}
      )
    },
  }
}
```

**Comment by IndexXuan** [comment]
dont know why index sbould be index.html while subpage can be subpage/index.html?

**Comment by patarapolw** [comment]
Default browser behavior. When opening `location.origin`, it will redirect to `location.origin + '/index.html'`. You cannot change that.

**Comment by patarapolw** [comment]
> dont know why index sbould be index.html(cannot it index/index.html) while subpage can be subpage/index.html?

Also that, when mpa plugin is installed, both `./index.html` and `./src/pages/index.html` stopped working.

**Comment by IndexXuan** [comment]
you can use yours or vite native config. dont really know how index.html src/index.html **stop working** mean.

**Comment by patarapolw** [comment]
> dont really know how index.html src/index.html stop working mean.

No matter I want tried, `dist/index.html` WILL NOT BE GENERATED.
