### ISSUE TITLE
Cannot disable `server.open`

### ISSUE THREAD

**Issue by patarapolw** [IndexXuan/vite-plugin-mpa#7]
This is the culprit - https://github.com/IndexXuan/vite-plugin-mpa/blob/90d1ac1900ef1fe28ed1b699be4e037830ef5452/src/index.ts#L33

I cannot set `""` or `false` as an option.

I think you shouldn't even try to modify `server.open` in the first place.

**Comment by IndexXuan** [comment]
will support not open
