### ISSUE TITLE
detail page by id

### ISSUE THREAD

**Issue by guobin211** [IndexXuan/vite-plugin-mpa#8]
### dev proxy

add proxy from **/pageName/id/index.html**  to  **/pageName/index.html**

```js
    // getHistoryReWriteRuleList

    list.push({
      from: new RegExp(`^/${pageName}/[a-z0-9]+/index.html$`), // support detailPageName/id/index.html
      to,
    })

```

**Comment by IndexXuan** [comment]
not common usecase here. can you explain more?

**Comment by IndexXuan** [comment]
detailId should be router params or query. not real fs path and do hack here.
